language: node_js
node_js:
- '5'
env:
- NODE_ENV=TEST CXX=g++-4.8
addons:
  ssh_known_hosts: 95.85.25.10
install:
- travis_retry npm install -g node-gyp
- travis_retry npm install
- sleep 15
script:
- travis_retry npm run build
- travis_retry npm run lint
- travis_retry npm test
after_success:
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- rm -rf src/
- rm -rf node_modules/
- tar -czf jseminck-be-api-aws.tgz .
- scp jseminck-be-api-aws.tgz deploy@95.85.25.10:/home/apps/
- ssh deploy@95.85.25.10 'source ~/.bash_profile && cd /home/apps/ && ./deploy.sh jseminck-be-api-aws'
before_install:
- openssl aes-256-cbc -K $encrypted_d6841531a428_key -iv $encrypted_d6841531a428_iv
  -in deploy-key.enc -out deploy-key -d
